### ISSUE TITLE
New feature: Custom routes & DNS

### ISSUE THREAD

**Issue by jlnemirova** [xterm-inator/microguard#23]
Can you add an enviroment for pushing certain routes and DNS address?

**Comment by jlnemirova** [comment]
Sorry. I've found  ROUTEROS_WIREGUARD_ALLOWED_IPS and ROUTEROS_WIREGUARD_DNS. Please add this into docs

**Comment by xterm-inator** [comment]
Hey, Thanks for your input. I'm glad you found a way to get it working; I'll add the extra options to the readme.
