### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by aleks-spv** [xterm-inator/microguard#26]
Hi
start compose

> version: '3.8'
> services:
>   microguard:
>     image: ghcr.io/xterm-inator/microguard:latest
>     container_name: microguard
>     restart: always
>     ports:
>       - 80:80
>     volumes:
>       - /path/to/data:/opt/app/storage
>     environment:
>       - APP_KEY=mykey
>       - GOOGLE_CLIENT_ID=
>      - GOOGLE_CLIENT_SECRET=
>      - GOOGLE_REDIRECT_URL=https://my.public.address/api/auth/oauth/google/callback
>       - ROUTEROS_HOST=192.168.0.1
>       - ROUTEROS_PORT=8728
>       - ROUTEROS_USER=wireguard
>       - ROUTEROS_PASS=wireguard pass
>       - ROUTEROS_WIREGUARD_INTERFACE=wireguard
>       - ROUTEROS_WIREGUARD_ENDPOINT=192.168.0.1:13231
>       - APP_URL=https://my.public.address
> 

create user
`docker compose exec microguard php artisan app:create-user admin@xterm.me admin `
can't login
docker logs microguard

` 500    POST /api/auth ..................................... 25.15 mb 80.23 ms
[2024-04-24 08:50:03] local.ERROR: Session store not set on request. {"userId":2,"exception":"[object] (RuntimeException(code: 0): Session store not set on request. at /opt/app/vendor/laravel/framework/src/Illuminate/Http/Request.php:564)
`

**Comment by xterm-inator** [comment]
Hey,

"Session store not set on request" errors are normally caused when the browser is accessing the server from an address that is different to the APP_URL set in the environment variables.

Try setting this to the address you are using, can be localhost, an IP address or a domain eg. http://localhost:8000

Hope this helps.

**Comment by aleks-spv** [comment]
Happened! Thank you very much for your work! Cool project!
