### ISSUE TITLE
could I host it internally without google sso

### ISSUE THREAD

**Issue by lazee486** [xterm-inator/microguard#7]
amazing looking app just dont want to be using google sign on :) was looking for my homelab

**Comment by xterm-inator** [comment]
Not currently, but it is on my list of things to do. I should be able to make an update for this over the next couple of nights.

**Comment by xterm-inator** [comment]
#10 Adds the ability to use the site without google sso. This adds basic user auth and asking for a password when creating users when a google ID is not provided.

**Comment by lazee486** [comment]
Awesome! Will test asap and thanks for the fast work!
